name: CI-CD

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Format check
        run: |
          pip install black
          black --check .

      - name: Type check
        run: |
          pip install mypy
          mypy app/

      - name: Linting
        run: |
          pip install ruff
          ruff check .

      - name: Safety check
        run: |
          pip install pip-audit
          pip-audit --fail-on=all

      - name: Run Pytest
        run: pytest
